#!/bin/bash

a="$(cat spells/* | grep -c 'crushing damage')"
echo "$a spells do crushing damage"
a="$(cat spells/* | grep -c 'piercing damage')"
echo "$a spells do piercing damage"
a="$(cat spells/* | grep -c 'slashing damage')"
echo "$a spells do slashing damage"
a="$(cat spells/* | grep -c 'acid damage')"
echo "$a spells do acid damage"
a="$(cat spells/* | grep -c 'poison damage')"
echo "$a spells do poison damage"
a="$(cat spells/* | grep -c 'fire damage')"
echo "$a spells do fire damage"
a="$(cat spells/* | grep -c 'cold damage')"
echo "$a spells do cold damage"
a="$(cat spells/* | grep -c 'electric damage')"
echo "$a spells do electric damage"
a="$(cat spells/* | grep -c 'necrotic damage')"
echo "$a spells do necrotic damage"
a="$(cat spells/* | grep -c 'sonic damage')"
echo "$a spells do sonic damage"
a="$(cat spells/* | grep -c 'psychic damage')"
echo "$a spells do psychic damage"
a="$(cat spells/* | grep -c 'force damage')"
echo "$a spells do force damage"
echo "Be aware that a spell can do two different types of damage"